---
# Entradas obrigatórias.
#
# Estas entradas serão verificadas em todas as execuções.
# Se uma entrada estiver ausente, ela será incluída.
# O Survey não poderá removê-las.
# O campo aliases é opcional.

windows_hosts_required:

  - ip: "10.10.10.10"
    name: "servidor-aplicacao.empresa.local"

  - ip: "10.10.10.20"
    name: "servidor-banco.empresa.local"
    aliases:
      - "servidor-banco"
      - "db01"

  - ip: "10.10.10.30"
    name: "servidor-monitoramento.empresa.local"