---
- name: Coletar administradores locais via SSH
  hosts: all
  gather_facts: false

  vars:
    administradores_permitidos:
      - mabreu
      - mabra

  tasks:

    - name: Criar pasta C:\Temp
      raw: |
        New-Item -Path 'C:\Temp' -ItemType Directory -Force
      register: pasta

    - name: Coletar administradores locais
      raw: |
        $hostname = hostname

        $saida = @()

        $saida += "========================================="
        $saida += "Servidor: $hostname"
        $saida += "Data: $(Get-Date -Format 'dd/MM/yyyy HH:mm:ss')"
        $saida += "========================================="
        $saida += ""
        $saida += "ADMINISTRADORES LOCAIS"
        $saida += ""

        net localgroup Administrators
      register: admins

    - name: Exibir resultado
      debug:
        var: admins.stdout_lines