---
- name: Teste de escrita
  hosts: windows
  gather_facts: false

  tasks:

    - name: Criar C:\Temp
      ansible.windows.win_shell: |
        New-Item -Path C:\Temp -ItemType Directory -Force
      register: pasta

    - debug:
        var: pasta.stdout

    - name: Criar arquivo de teste
      ansible.windows.win_shell: |
        "Teste AWX $(Get-Date)" | Out-File C:\Temp\adm.txt -Encoding UTF8 -Force
      register: arquivo

    - debug:
        var: arquivo.stdout

    - name: Validar arquivo
      ansible.windows.win_shell: |
        Test-Path C:\Temp\adm.txt
      register: validacao

    - debug:
        var: validacao.stdout