[windows_winrm]
winsrv01 ansible_host=10.55.10.11
winsrv02 ansible_host=10.55.10.12

[windows_winrm:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
ansible_user=administrator
# ansible_password=SUASENHA   # recomendo usar Ansible Vault em produção


[windows_ssh]
winsrv01 ansible_host=10.55.10.11
winsrv02 ansible_host=10.55.10.12

[windows_ssh:vars]
ansible_connection=ssh
ansible_shell_type=powershell
ansible_user=administrator
# Escolha UM dos métodos de autenticação abaixo:

# Opção A - senha (recomendo usar Ansible Vault em produção)
# ansible_password=SUASENHA

# Opção B - chave pública/privada (OpenSSH no Windows suporta authorized_keys)
# ansible_ssh_private_key_file=~/.ssh/id_rsa_windows

# Evita prompt de host key em ambientes de teste (não recomendado em produção)
# ansible_ssh_common_args='-o StrictHostKeyChecking=no'
