- name: Update Linux System
  hosts: all
  become: false   # impede sudo no Gathering Facts

  tasks:
    - name: YUM | Update System
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution in ["CentOS", "RedHat"]
      become: true   # sudo apenas aqui

    - name: APT | Update Cache
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]
      become: true   # sudo apenas aqui

    - name: APT | Update System
      apt:
        name: "*"
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]
      become: true   # sudo apenas aqui
